### ISSUE TITLE
Problema al reconocer los caracteres de la placa

### ISSUE THREAD

**Issue by Aksh97** [ankandrew/ConvALPR#6]
Hola, gracias por el increíble trabajo. Cuando pruebo el modelo con un conjunto determinado de videos, funciona bien. Pero cuando estoy probando con video fuera de él, está detectando la placa de matrícula pero no puede obtener el reconocimiento de números/alfabetos de ella. ¿Crees que necesito cambiar algunos parámetros para que funcione?
Gracias por adelantado.
![screenshot_](https://user-images.githubusercontent.com/36452065/200240330-282346f2-275b-46d3-afda-c85d7082b389.png)

**Comment by ankandrew** [comment]
Hi @Aksh97! ConvALPR consists of an object detector and an OCR. I trained the OCR only with Argentinian license plates, so that's why it's failing recognize the text.

The OCR used can be found in this repo: [cnn-ocr-lp](https://github.com/ankandrew/cnn-ocr-lpr). To overcome this issue I suggest you train the OCR module with a more diverse dataset (i.e. the country you are targeting or even from different countries). The tutorial for that is here https://github.com/ankandrew/cnn-ocr-lp/wiki/Train-your-custom-OCR. After trained you can easily plug that model here

**Comment by Aksh97** [comment]
Thanks a lot for the response. @ankandrew. I wanted to train for USA number plates, do you have any suggestions on where I can get the dataset, I searched a lot but could not find it. Any suggestions would be helpful at the moment.

**Comment by ankandrew** [comment]
@Aksh97 I don't know of any dataset for US plates I can recommend.

But what I'm thinking that might work out is to create a synthetic dataset generator and train the OCR model with that (something like this https://randomlicenseplate.com/license-plate).
